#!/bin/bash

CUR_DIR="$(dirname `realpath $0`)"

cd obj_dir

ccache g++ -Os  -I.  -MMD -I"$CUR_DIR"/include -I"$CUR_DIR"/include/vltstd -DVERILATOR=1 -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TIMING=1 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -DVM_TRACE_SAIF=0 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-int-in-bool-context -Wno-shadow -Wno-sign-compare -Wno-subobject-linkage -Wno-tautological-compare -Wno-uninitialized -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable    -DVL_TIME_CONTEXT   -fcoroutines -c -o verilated.o "$CUR_DIR"/include/verilated.cpp
ccache g++ -Os  -I.  -MMD -I"$CUR_DIR"/include -I"$CUR_DIR"/include/vltstd -DVERILATOR=1 -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TIMING=1 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -DVM_TRACE_SAIF=0 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-int-in-bool-context -Wno-shadow -Wno-sign-compare -Wno-subobject-linkage -Wno-tautological-compare -Wno-uninitialized -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable    -DVL_TIME_CONTEXT   -fcoroutines -c -o verilated_timing.o "$CUR_DIR"/include/verilated_timing.cpp
ccache g++ -Os  -I.  -MMD -I"$CUR_DIR"/include -I"$CUR_DIR"/include/vltstd -DVERILATOR=1 -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TIMING=1 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -DVM_TRACE_SAIF=0 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-int-in-bool-context -Wno-shadow -Wno-sign-compare -Wno-subobject-linkage -Wno-tautological-compare -Wno-uninitialized -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable    -DVL_TIME_CONTEXT   -fcoroutines -c -o verilated_threads.o "$CUR_DIR"/include/verilated_threads.cpp
python3 "$CUR_DIR"/bin/verilator_includer -DVL_INCLUDE_OPT=include Vexample.cpp Vexample___024root__0.cpp Vexample___024unit__03a__03aBase__Vclpkg__0.cpp Vexample___024unit__03a__03aDerived__Vclpkg__0.cpp Vexample_std__03a__03asemaphore__Vclpkg__0.cpp Vexample_std__03a__03aprocess__Vclpkg__0.cpp Vexample__main.cpp Vexample___024root__Slow.cpp Vexample___024root__0__Slow.cpp Vexample___024unit__Slow.cpp Vexample___024unit__0__Slow.cpp Vexample_std__Slow.cpp Vexample_std__0__Slow.cpp Vexample___024unit__03a__03aBase__Vclpkg__Slow.cpp Vexample___024unit__03a__03aBase__Vclpkg__0__Slow.cpp Vexample___024unit__03a__03aDerived__Vclpkg__Slow.cpp Vexample___024unit__03a__03aDerived__Vclpkg__0__Slow.cpp Vexample_std__03a__03asemaphore__Vclpkg__Slow.cpp Vexample_std__03a__03asemaphore__Vclpkg__0__Slow.cpp Vexample_std__03a__03aprocess__Vclpkg__Slow.cpp Vexample_std__03a__03aprocess__Vclpkg__0__Slow.cpp Vexample__Syms__Slow.cpp > Vexample__ALL.cpp
ccache g++ -Os  -I.  -MMD -I"$CUR_DIR"/include -I"$CUR_DIR"/include/vltstd -DVERILATOR=1 -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TIMING=1 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -DVM_TRACE_SAIF=0 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-int-in-bool-context -Wno-shadow -Wno-sign-compare -Wno-subobject-linkage -Wno-tautological-compare -Wno-uninitialized -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable    -DVL_TIME_CONTEXT   -fcoroutines -c -o Vexample__ALL.o Vexample__ALL.cpp
g++ -fuse-ld=mold   verilated.o verilated_timing.o verilated_threads.o Vexample__ALL.o    -pthread -lpthread -latomic   -o Vexample

cd -
